/* written by `vanta-tool uifixture` - dev/browser preview only (the app gets this from the host) */
window.VantaDev = { library: {
  "type": "library",
  "app": {
    "name": "Vanta",
    "version": "0.3.1",
    "production": true,
    "lang": "nl",
    "ackTimeout": 30000
  },
  "games": [
    {
      "id": "far-cry-5",
      "name": "Far Cry 5",
      "short": "FC5",
      "badge": "build 18766066",
      "version": "Steam-build 18766066 (juli 2025) - onbevestigd",
      "cheatCount": 16,
      "steamAppId": 552520,
      "categories": [
        "shooter",
        "open world"
      ],
      "antiCheat": false,
      "onlineOnly": false,
      "group": "all",
      "art": {
        "tint": "#4ADE80",
        "motif": "ridge",
        "sky": [
          "#0A1410",
          "#1F4A3A"
        ],
        "horizon": "#E8D38A",
        "ground": "#050A08"
      },
      "process": "FarCry5.exe",
      "cheats": [],
      "lazy": true
    },
    {
      "id": "far-cry-6",
      "name": "Far Cry 6",
      "short": "FC6",
      "badge": "1.8.0",
      "version": "1.8.0 (build 20-07-2025, Ubisoft Connect/Steam)",
      "cheatCount": 20,
      "steamAppId": 2369390,
      "categories": [
        "shooter",
        "open world"
      ],
      "antiCheat": false,
      "onlineOnly": false,
      "group": "all",
      "art": {
        "tint": "#FB923C",
        "motif": "ridge",
        "sky": [
          "#1A0F0A",
          "#5A2A18"
        ],
        "horizon": "#FFC58A",
        "ground": "#0C0604"
      },
      "process": "FarCry6.exe",
      "cheats": [],
      "lazy": true
    },
    {
      "id": "the-last-caretaker",
      "name": "The Last Caretaker",
      "short": "LC",
      "badge": "EA 0.8.5",
      "version": "Early Access 0.8.5.651238",
      "cheatCount": 16,
      "steamAppId": 1783560,
      "categories": [
        "survival",
        "sci-fi",
        "open world"
      ],
      "antiCheat": false,
      "onlineOnly": false,
      "group": "recent",
      "art": {
        "tint": "#5CC8B8",
        "motif": "sea",
        "sky": [
          "#07131F",
          "#17465A"
        ],
        "horizon": "#F0A56E",
        "ground": "#061015"
      },
      "process": "VoyageSteam-Win64-Shipping.exe",
      "cheats": [],
      "lazy": true
    }
  ],
  "selected": "the-last-caretaker"
}, games: {
  "far-cry-5": {
    "id": "far-cry-5",
    "name": "Far Cry 5",
    "short": "FC5",
    "badge": "build 18766066",
    "version": "Steam-build 18766066 (juli 2025) - onbevestigd",
    "process": "FarCry5.exe",
    "steamAppId": 552520,
    "categories": [
      "shooter",
      "open world"
    ],
    "antiCheat": false,
    "onlineOnly": false,
    "cheatCount": 16,
    "notes": [
      "EasyAntiCheat is met de laatste patch (november 2019) uit Far Cry 5 verwijderd. Vindt Vanta toch EasyAntiCheat-bestanden in je installatie (een oude versie), dan weigert Vanta.",
      "Alle cheats komen uit tabellen van 2018 en zijn niet getest in de huidige build. Controleer eerst met: Vanta.exe --verify far-cry-5",
      "Bewust weggelaten: zilverstaven (premiumvaluta die ook voor echt geld te koop is), 'unlock all store items' (ontgrendelt ook betaalde items), Arcade-cheats en cheats met vaste adressen.",
      "Het Ubisoft-id 856 is niet bevestigd; de Steam-installatie wordt altijd gevonden.",
      "Maak een backup van je save voordat je cheats gebruikt."
    ],
    "scope": "Alleen voor de solo-campagne. Niet gebruiken in co-op, Arcade of online.",
    "install": {
      "primary": {
        "store": "steam",
        "storeName": "Steam",
        "installed": true,
        "dir": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FarCry5",
        "build": "18766066",
        "launch": "steam://run/552520"
      },
      "owned": [],
      "all": [
        {
          "store": "steam",
          "storeName": "Steam",
          "installed": true,
          "dir": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FarCry5",
          "build": "18766066",
          "launch": "steam://run/552520"
        }
      ]
    },
    "art": {
      "tint": "#4ADE80",
      "motif": "ridge",
      "sky": [
        "#0A1410",
        "#1F4A3A"
      ],
      "horizon": "#E8D38A",
      "ground": "#050A08"
    },
    "statusVersion": "label:Steam-build 18766066 (juli 2025) - onbevestigd",
    "cheats": [
      {
        "id": "godmode",
        "section": "speler",
        "type": "toggle",
        "name": "Godmode",
        "icon": "shield",
        "hotkey": "Numpad1",
        "defaultHotkey": "Numpad1",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Je gezondheid wordt steeds teruggezet op het maximum.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_stamina",
        "section": "speler",
        "type": "toggle",
        "name": "Oneindig uithoudingsvermogen",
        "icon": "bolt",
        "hotkey": "Numpad2",
        "defaultHotkey": "Numpad2",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Sprinten kost geen uithoudingsvermogen.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_oxygen",
        "section": "speler",
        "type": "toggle",
        "name": "Oneindig zuurstof",
        "icon": "heart",
        "hotkey": "Numpad3",
        "defaultHotkey": "Numpad3",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Zuurstof onder water raakt niet op.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "no_fall_damage",
        "section": "speler",
        "type": "toggle",
        "name": "Geen valschade",
        "icon": "jump",
        "hotkey": "Ctrl+Numpad3",
        "defaultHotkey": "Ctrl+Numpad3",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Vallen doet geen schade.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_ammo",
        "section": "wapens",
        "type": "toggle",
        "name": "Oneindig munitie",
        "icon": "ammo",
        "hotkey": "Numpad4",
        "defaultHotkey": "Numpad4",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Munitie wordt niet afgetrokken bij schieten.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "no_recoil",
        "section": "wapens",
        "type": "toggle",
        "name": "Geen terugslag",
        "icon": "crosshair",
        "hotkey": "Numpad5",
        "defaultHotkey": "Numpad5",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Wapens hebben geen terugslag.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "no_spread",
        "section": "wapens",
        "type": "toggle",
        "name": "Geen kogelspreiding",
        "icon": "target",
        "hotkey": "Ctrl+Numpad5",
        "defaultHotkey": "Ctrl+Numpad5",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Kogels gaan precies waar je richt.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "no_sway",
        "section": "wapens",
        "type": "toggle",
        "name": "Geen wapenzwaai",
        "icon": "crosshair",
        "hotkey": "Numpad6",
        "defaultHotkey": "Numpad6",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Je vizier zwaait niet bij het richten.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "stealth",
        "section": "extra",
        "type": "toggle",
        "name": "Onopgemerkt (stealth)",
        "icon": "eye",
        "hotkey": "Numpad7",
        "defaultHotkey": "Numpad7",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Vijanden merken je niet op.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "vehicle_godmode",
        "section": "voertuig",
        "type": "toggle",
        "name": "Onverwoestbare voertuigen",
        "icon": "car",
        "hotkey": "Numpad8",
        "defaultHotkey": "Numpad8",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Voertuigen worden steeds hersteld naar maximale gezondheid. Let op: dit kan ook voor voertuigen van vijanden gelden.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_missiles",
        "section": "voertuig",
        "type": "toggle",
        "name": "Oneindig raketten & flares",
        "icon": "fire",
        "hotkey": "Numpad9",
        "defaultHotkey": "Numpad9",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Raketten en flares van vliegtuigen/helikopters raken niet op.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_bombs",
        "section": "voertuig",
        "type": "toggle",
        "name": "Oneindig bommen",
        "icon": "fire",
        "hotkey": "Ctrl+Numpad9",
        "defaultHotkey": "Ctrl+Numpad9",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Bommen van vliegtuigen raken niet op.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "money",
        "section": "punten",
        "type": "toggle",
        "name": "Geld bewerken",
        "icon": "coin",
        "hotkey": "Ctrl+Numpad1",
        "defaultHotkey": "Ctrl+Numpad1",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Maakt je geld (dollars) bewerkbaar. Aanzetten, dan het spel laden en eenmaal TAB (inventaris) indrukken; daarna verschijnt de waarde.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "money_value",
        "section": "punten",
        "type": "number",
        "name": "Geld",
        "icon": "coin",
        "min": 0,
        "max": 9999999,
        "step": 1000,
        "format": "{v}",
        "hint": "Druk eenmaal op TAB in het spel",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Je huidige geld (dollars).",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "perks",
        "section": "punten",
        "type": "toggle",
        "name": "Perkpunten bewerken",
        "icon": "star",
        "hotkey": "Ctrl+Numpad2",
        "defaultHotkey": "Ctrl+Numpad2",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Maakt je perkpunten bewerkbaar. Geef eenmaal een perkpunt uit, dan verschijnt de waarde.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "perks_value",
        "section": "punten",
        "type": "number",
        "name": "Perkpunten",
        "icon": "star",
        "min": 0,
        "max": 999,
        "step": 1,
        "format": "{v}",
        "hint": "Geef eenmaal een perkpunt uit",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Je huidige perkpunten.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      }
    ]
  },
  "far-cry-6": {
    "id": "far-cry-6",
    "name": "Far Cry 6",
    "short": "FC6",
    "badge": "1.8.0",
    "version": "1.8.0 (build 20-07-2025, Ubisoft Connect/Steam)",
    "process": "FarCry6.exe",
    "steamAppId": 2369390,
    "categories": [
      "shooter",
      "open world"
    ],
    "antiCheat": false,
    "onlineOnly": false,
    "cheatCount": 20,
    "notes": [
      "Far Cry 6 heeft geen anti-cheat (alleen Denuvo/VMProtect-DRM). Gebruik de cheats alleen solo: co-op-sessies zijn online en daar hoort niemand last van jou te hebben.",
      "Alle cheats zijn nog niet getest in build 1.8.0. Controleer eerst met: Vanta.exe --verify far-cry-6",
      "Zet de hash-vingerafdruk uit het --verify-rapport in supportedVersions zodra de build bevestigd is.",
      "Maak een backup van je save: Ubisoft Connect\\savegames\\<account>\\5266 (Steam-versie: map 920)."
    ],
    "scope": "Alleen voor de solo-campagne. Niet gebruiken in co-op of online.",
    "install": {
      "primary": {
        "store": "ubisoft",
        "storeName": "Ubisoft Connect",
        "installed": true,
        "dir": "C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\games\\Far Cry 6",
        "build": "5266",
        "launch": "uplay://launch/5266/0"
      },
      "owned": [],
      "all": [
        {
          "store": "ubisoft",
          "storeName": "Ubisoft Connect",
          "installed": true,
          "dir": "C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\games\\Far Cry 6",
          "build": "5266",
          "launch": "uplay://launch/5266/0"
        }
      ]
    },
    "art": {
      "tint": "#FB923C",
      "motif": "ridge",
      "sky": [
        "#1A0F0A",
        "#5A2A18"
      ],
      "horizon": "#FFC58A",
      "ground": "#0C0604"
    },
    "statusVersion": "label:1.8.0 (build 20-07-2025, Ubisoft Connect/Steam)",
    "cheats": [
      {
        "id": "godmode",
        "section": "speler",
        "type": "toggle",
        "name": "Godmode",
        "icon": "shield",
        "hotkey": "Numpad1",
        "defaultHotkey": "Numpad1",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Je neemt geen schade: de aanroep die schade op de speler toepast wordt overgeslagen.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_stamina",
        "section": "speler",
        "type": "toggle",
        "name": "Oneindig uithoudingsvermogen",
        "icon": "bolt",
        "hotkey": "Numpad2",
        "defaultHotkey": "Numpad2",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Sprinten en klimmen kosten geen uithoudingsvermogen.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_oxygen",
        "section": "speler",
        "type": "toggle",
        "name": "Oneindig zuurstof",
        "icon": "heart",
        "hotkey": "Numpad3",
        "defaultHotkey": "Numpad3",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Zuurstof onder water raakt niet op.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_ammo",
        "section": "wapens",
        "type": "toggle",
        "name": "Oneindig munitie",
        "icon": "ammo",
        "hotkey": "Numpad4",
        "defaultHotkey": "Numpad4",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Het magazijn van je wapen blijft gevuld (zet de huidige clip op 99).",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "no_reload",
        "section": "wapens",
        "type": "toggle",
        "name": "Niet herladen",
        "icon": "ammo",
        "hotkey": "Ctrl+Numpad4",
        "defaultHotkey": "Ctrl+Numpad4",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Het magazijn wordt niet leeg, dus je hoeft niet te herladen.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_throwables",
        "section": "inventaris",
        "type": "toggle",
        "name": "Oneindig werpwapens & handelswaar",
        "icon": "grenade",
        "hotkey": "Numpad5",
        "defaultHotkey": "Numpad5",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Werpwapens (granaten, molotovs) en handelsgoederen worden niet afgetrokken. Volgens de auteur kun je zo ook handelswaar blijven verkopen voor Yaran-peso's.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "no_recoil",
        "section": "wapens",
        "type": "toggle",
        "name": "Geen terugslag",
        "icon": "crosshair",
        "hotkey": "Numpad6",
        "defaultHotkey": "Numpad6",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Wapens hebben geen terugslag.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "super_accuracy",
        "section": "wapens",
        "type": "toggle",
        "name": "Superprecisie",
        "icon": "target",
        "hotkey": "Ctrl+Numpad6",
        "defaultHotkey": "Ctrl+Numpad6",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Kogelspreiding wordt vastgezet op een lage waarde.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "no_overheat",
        "section": "wapens",
        "type": "toggle",
        "name": "Geluiddemper raakt nooit oververhit",
        "icon": "snow",
        "hotkey": "Numpad7",
        "defaultHotkey": "Numpad7",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Geluiddempers (en wapenhitte op dezelfde waarde) blijven op 0.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_supremo",
        "section": "wapens",
        "type": "toggle",
        "name": "Oneindig Supremo",
        "icon": "bolt",
        "hotkey": "Numpad8",
        "defaultHotkey": "Numpad8",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "De Supremo-rugzak laadt niet leeg; je kunt de speciale aanval steeds gebruiken.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "vehicle_godmode",
        "section": "voertuig",
        "type": "toggle",
        "name": "Onverwoestbare voertuigen",
        "icon": "car",
        "hotkey": "Numpad9",
        "defaultHotkey": "Numpad9",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Voertuigen nemen geen schade. Let op: dit kan ook voor voertuigen van vijanden gelden.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "free_craft",
        "section": "inventaris",
        "type": "toggle",
        "name": "Gratis craften",
        "icon": "hammer",
        "hotkey": "Ctrl+Numpad1",
        "defaultHotkey": "Ctrl+Numpad1",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Upgrades en uitrusting maken kost geen materialen.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "resource_mult",
        "section": "punten",
        "type": "toggle",
        "name": "Grondstoffen- en geldvermenigvuldiger",
        "icon": "multiply",
        "hotkey": "Ctrl+Numpad2",
        "defaultHotkey": "Ctrl+Numpad2",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Opgepakte grondstoffen en geld worden vermenigvuldigd (standaard x2; stel hieronder in).",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "resource_mult_value",
        "section": "punten",
        "type": "number",
        "name": "Vermenigvuldiger",
        "icon": "multiply",
        "min": 1,
        "max": 100,
        "step": 1,
        "format": "{v}",
        "hint": "Nog niet beschikbaar",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Factor voor opgepakte grondstoffen/geld.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "xp_mult",
        "section": "punten",
        "type": "toggle",
        "name": "XP-bonus",
        "icon": "star",
        "hotkey": "Ctrl+Numpad3",
        "defaultHotkey": "Ctrl+Numpad3",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Experimenteel: kan de game laten crashen. Sla eerst op.",
        "description": "Telt extra XP op bij elke XP-winst (standaard +100). Volgens de auteur werkt het vooral bij het vernietigen van voertuigen.",
        "confidence": "experimental",
        "baseConfidence": "experimental",
        "enabled": false
      },
      {
        "id": "xp_mult_value",
        "section": "punten",
        "type": "number",
        "name": "XP-bonus per keer",
        "icon": "star",
        "min": 0,
        "max": 100000,
        "step": 50,
        "format": "{v}",
        "hint": "Nog niet beschikbaar",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Hoeveel XP er per keer extra bij komt.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "speed",
        "section": "extra",
        "type": "toggle",
        "name": "Snelheid",
        "icon": "speed",
        "hotkey": "Ctrl+Numpad7",
        "defaultHotkey": "Ctrl+Numpad7",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Past je bewegingssnelheid aan (waarde hieronder).",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "speed_value",
        "section": "extra",
        "type": "number",
        "name": "Snelheidswaarde",
        "icon": "speed",
        "min": 0,
        "max": 1,
        "step": 0.005,
        "format": "{v}",
        "hint": "Nog niet beschikbaar",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Snelheidswaarde van de speler (tabel-standaard 0,01).",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "super_jump",
        "section": "extra",
        "type": "toggle",
        "name": "Superhoge sprong",
        "icon": "jump",
        "hotkey": "Ctrl+Numpad8",
        "defaultHotkey": "Ctrl+Numpad8",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Je springt hoger.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "stealth",
        "section": "extra",
        "type": "toggle",
        "name": "Onopgemerkt (stealth)",
        "icon": "eye",
        "hotkey": "Ctrl+Numpad9",
        "defaultHotkey": "Ctrl+Numpad9",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Experimenteel: kan de game laten crashen. Sla eerst op.",
        "description": "Vijanden merken je niet op.",
        "confidence": "experimental",
        "baseConfidence": "experimental",
        "enabled": false
      }
    ]
  },
  "the-last-caretaker": {
    "id": "the-last-caretaker",
    "name": "The Last Caretaker",
    "short": "LC",
    "badge": "EA 0.8.5",
    "version": "Early Access 0.8.5.651238",
    "process": "VoyageSteam-Win64-Shipping.exe",
    "steamAppId": 1783560,
    "categories": [
      "survival",
      "sci-fi",
      "open world"
    ],
    "antiCheat": false,
    "onlineOnly": false,
    "cheatCount": 16,
    "notes": [
      "Alleen Infinite Battery is bevestigd werkend in 0.8.5.651238; alle andere cheats zijn ongetest en falen veilig (niets gepatcht) als hun AOB niet uniek is.",
      "XP waarde en Enhancer-bonus gebruiken een hook die automatisch wordt geplaatst bij het koppelen. XP verschijnt nadat je eenmaal XP verdient.",
      "Maak een backup van je save: %LOCALAPPDATA%\\Voyage\\Saved\\SaveGames",
      "Vul supportedVersions (fileVersion/peTimestamp/moduleSize) aan met de vingerafdruk uit het log zodra de versie is bevestigd."
    ],
    "install": {
      "owned": [],
      "all": []
    },
    "art": {
      "tint": "#5CC8B8",
      "motif": "sea",
      "sky": [
        "#07131F",
        "#17465A"
      ],
      "horizon": "#F0A56E",
      "ground": "#061015"
    },
    "statusVersion": "fileVersion=0.8.5.651238, peTimestamp=?, moduleSize=65536",
    "cheats": [
      {
        "id": "inf_battery",
        "section": "speler",
        "type": "toggle",
        "name": "Infinite Battery",
        "icon": "battery",
        "hotkey": "F5",
        "defaultHotkey": "F5",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "description": "Geen stroomverbruik: skipt de 'subsd' in de gedeelde elektriciteits-drain (speler-battery en elektrisch gereedschap/pak).",
        "confidence": "confirmed",
        "baseConfidence": "confirmed",
        "enabled": false
      },
      {
        "id": "inf_health",
        "section": "speler",
        "type": "toggle",
        "name": "Infinite Health",
        "icon": "heart",
        "hotkey": "F6",
        "defaultHotkey": "F6",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Speler neemt geen schade. Neem eenmaal schade zodat het HP-adres wordt vastgelegd.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "health_current",
        "section": "speler",
        "type": "number",
        "name": "Health huidig",
        "icon": "heart",
        "min": 0,
        "max": 100000,
        "step": 10,
        "format": "{v}",
        "hint": "Zet Infinite Health aan en neem eenmaal schade",
        "note": "Niet geverifieerd voor deze versie.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "health_max",
        "section": "speler",
        "type": "number",
        "name": "Health max",
        "icon": "heart",
        "min": 0,
        "max": 100000,
        "step": 10,
        "format": "{v}",
        "hint": "Zet Infinite Health aan en neem eenmaal schade",
        "note": "Niet geverifieerd voor deze versie.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "no_weight",
        "section": "speler",
        "type": "toggle",
        "name": "Geen gewicht",
        "icon": "weight",
        "hotkey": "F7",
        "defaultHotkey": "F7",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Draaglimiet genegeerd (pak eenmaal een item op of leg er een neer om te verversen).",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_ammo",
        "section": "wapens",
        "type": "toggle",
        "name": "Infinite Ammo",
        "icon": "ammo",
        "hotkey": "F8",
        "defaultHotkey": "F8",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Bolt pistool/geweer/sniper: schieten verbruikt geen munitie, herladen werkt.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_grenades",
        "section": "wapens",
        "type": "toggle",
        "name": "Infinite Grenades",
        "icon": "grenade",
        "hotkey": "F9",
        "defaultHotkey": "F9",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Granaten dalen niet (kan ook andere verbruiksitems raken).",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_charge",
        "section": "wapens",
        "type": "toggle",
        "name": "Infinite wapenlading (elektrisch)",
        "icon": "bolt",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Elektrische wapens/vlammenwerper verbruiken geen lading.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "xp_value",
        "section": "punten",
        "type": "number",
        "name": "XP waarde",
        "icon": "bolt",
        "hotkeyInc": "Numpad+",
        "hotkeyDec": "Numpad-",
        "defaultHotkeyInc": "Numpad+",
        "defaultHotkeyDec": "Numpad-",
        "min": 0,
        "max": 9999999,
        "step": 1000,
        "format": "{v}",
        "sub": "Meer XP = level-up = skill- en enhancerpunten",
        "hint": "Verdien eenmaal XP in-game (bv. iets looten of recyclen)",
        "note": "Niet geverifieerd voor deze versie.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "xp_mult",
        "section": "punten",
        "type": "slider",
        "name": "XP multiplier",
        "icon": "multiply",
        "min": 1,
        "max": 10,
        "step": 1,
        "format": "×{v}",
        "hint": "XP-hook niet actief",
        "note": "Niet geverifieerd voor deze versie.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "enhancer_pts",
        "section": "punten",
        "type": "number",
        "name": "Enhancer-bonus",
        "icon": "gem",
        "hotkeyInc": "Shift+Numpad+",
        "hotkeyDec": "Shift+Numpad-",
        "defaultHotkeyInc": "Shift+Numpad+",
        "defaultHotkeyDec": "Shift+Numpad-",
        "min": 0,
        "max": 9999,
        "step": 1,
        "format": "{v}",
        "sub": "Extra punten; zichtbaar na openen enhancer-menu",
        "hint": "Enhancer-hook niet actief",
        "note": "Niet geverifieerd voor deze versie.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_jump",
        "section": "extra",
        "type": "toggle",
        "name": "Onbeperkt springen",
        "icon": "jump",
        "hotkey": "F10",
        "defaultHotkey": "F10",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "instant_build",
        "section": "extra",
        "type": "toggle",
        "name": "Direct bouwen",
        "icon": "hammer",
        "hotkey": "F11",
        "defaultHotkey": "F11",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "inf_petrol",
        "section": "extra",
        "type": "toggle",
        "name": "Infinite petrol",
        "icon": "fuel",
        "hotkey": "Ctrl+F8",
        "defaultHotkey": "Ctrl+F8",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Petrol (voertuigen/generator) daalt niet.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "free_craft",
        "section": "extra",
        "type": "toggle",
        "name": "Gratis craften",
        "icon": "cube",
        "hotkey": "Ctrl+F9",
        "defaultHotkey": "Ctrl+F9",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "Geen materialen nodig of verbruikt.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      },
      {
        "id": "dupe_items",
        "section": "extra",
        "type": "toggle",
        "name": "Items dupliceren bij splitsen",
        "icon": "copy",
        "hotkey": "Ctrl+F10",
        "defaultHotkey": "Ctrl+F10",
        "min": 0,
        "max": 999999,
        "step": 1,
        "format": "{v}",
        "note": "Niet geverifieerd voor deze versie.",
        "description": "De bronstapel daalt niet bij splitsen.",
        "confidence": "untested",
        "baseConfidence": "untested",
        "enabled": false
      }
    ]
  }
} };
