<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Vanta.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Iced" Version="1.21.0" />
    <EmbeddedResource Include="..\..\schema\game.schema.json" LogicalName="game.schema.json" />
    <PackageReference Include="JsonSchema.Net" Version="7.3.4" />
  </ItemGroup>
</Project>
